[package]
name = "create_one_nft"
version = "1.0.0"
authors = []

[addresses]

MyNFT = "0x9357f3115746bcf76e67e4206bfe0db98d4bff1a35bec131ab8d321abfd272b0"

[dev-addresses]

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
